CeladonCity_Condominiums_1F_Text_Meowth::
    .string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
    .string "DAVID: Proper recovery starts at\n"
    .string "home! I've got my PROTEIN BAR\l"
    .string "stash right here, and CLAIRE\l"
    .string "keeps the place running smooth.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
    .string "CLAIRE: Welcome! DAVID is usually\n"
    .string "at the GYM showing off his gains,\l"
    .string "but I'm so proud of him being the\l"
    .string "local Leader!$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
    .string "My dear POKéMON keep me company.\n"
    .string "MEOWTH even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
    .string "CLAIRE: I often visit the EMPIRE\n"
    .string "DEPT. STORE to stock up on supplies.\p"
    .string "I sometimes see DAISY there, she\n"
    .string "really loves her tea!$"

CeladonCity_Condominiums_1F_Text_Clefairy::
    .string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
    .string "NIDORAN♀: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
    .string "CELADON MANSION\n"
    .string "Manager's Suite$"

