FuchsiaCity_Text_DidYouTrySafariGame::
    .string "ELLIE: Did you try the SAFARI GAME?\p"
    .string "It's way more exciting than just\n"
    .string "watching hockey with NIKY!$"

FuchsiaCity_Text_SafariZoneZooInFront::
    .string "CHRIS: The WOBURN SAFARI PARK has\n"
    .string "a zoo in front of the entrance.\p"
    .string "Out back is the SAFARI GAME. I\n"
    .string "hope you brought plenty of Poké\l"
    .string "Balls!$"

FuchsiaCity_Text_WheresSara::
    .string "ERIK: Where's SARA?\n"
    .string "I said I'd meet her here.$"

FuchsiaCity_Text_ItemBallInThere::
    .string "That item ball in there…\n"
    .string "Were you wanting that?\p"
    .string "Me, too!\n"
    .string "…Huh? That's a POKéMON?$"

FuchsiaCity_Text_CitySign::
    .string "HUSTLER CITY\n"
    .string "Behold! It's Passion Pink!$"

FuchsiaCity_Text_SafariZoneSign::
    .string "POKéMON PARADISE\n"
    .string "WOBURN SAFARI PARK$"

FuchsiaCity_Text_SafariGameSign::
    .string "SAFARI GAME\n"
    .string "POKéMON-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
    .string "WOBURN SAFARI PARK\n"
    .string "WARDEN'S HOME$"

FuchsiaCity_Text_SafariZoneOfficeSign::
    .string "POKéMON PARADISE!\n"
    .string "Welcome to the WOBURN SAFARI PARK!\l"
    .string "WOBURN SAFARI PARK OFFICE$"

FuchsiaCity_Text_GymSign::
    .string "HUSTLER CITY POKéMON GYM\n"
    .string "LEADER: MILAN\l"
    .string "The Poisonous Ninja Master$"

FuchsiaCity_Text_ChanseySign::
    .string "Name: CHANSEY\n"
    .string "Catching one is all up to chance.$"

FuchsiaCity_Text_VoltorbSign::
    .string "Name: VOLTORB\n"
    .string "The very image of a POKé BALL.$"

FuchsiaCity_Text_KangaskhanSign::
    .string "Name: KANGASKHAN\p"
    .string "A maternal POKéMON that raises its\n"
    .string "young in a pouch on its belly.$"

FuchsiaCity_Text_SlowpokeSign::
    .string "Name: SLOWPOKE\n"
    .string "Friendly and very slow moving.$"

FuchsiaCity_Text_LaprasSign::
    .string "Name: LAPRAS\n"
    .string "AKA the king of the seas.$"

FuchsiaCity_Text_OmanyteSign::
    .string "Name: OMANYTE\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"

FuchsiaCity_Text_KabutoSign::
    .string "Name: KABUTO\n"
    .string "An extremely rare POKéMON that was\l"
    .string "regenerated from a fossil.$"

@ Unused. May have been meant to be the placeholder text for the zoo mons, similar to RB's "!" text
FuchsiaCity_Text_Ellipsis::
    .string "……$"

Text_SubstituteTeach::
    .string "Aww, I wish I was a KANGASKHAN\n"
    .string "baby.\p"
    .string "I'd love to be a substitute for the\n"
    .string "baby…\p"
    .string "And snuggle in the mother\n"
    .string "KANGASKHAN's belly pouch.\p"
    .string "But only POKéMON can use the\n"
    .string "technique SUBSTITUTE…\p"
    .string "Want me to teach SUBSTITUTE to\n"
    .string "one of your POKéMON?$"

Text_SubstituteDeclined::
    .string "Oh, really?\n"
    .string "SUBSTITUTE seems so fun…$"

Text_SubstituteWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "SUBSTITUTE?$"

Text_SubstituteTaught::
    .string "Boy, what I'd give to crawl inside\n"
    .string "a KANGASKHAN belly pouch…$"

FuchsiaCity_Text_MyFatherIsGymLeader::
    .string "JANHVI: MILAN is the LEADER of\n"
    .string "this town. He's my ninja mentor!\p"
    .string "I'm training to use POISON POKéMON\n"
    .string "just like him.$"

