FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
    .string "MILAN: I'm usually at the GYM,\n"
    .string "teaching the ways of the ninja.\p"
    .string "Welcome to my sanctuary in\n"
    .string "HUSTLER CITY!$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
    .string "Hmm?\n"
    .string "You've met BILL?\p"
    .string "He's my grandson!\p"
    .string "He always liked collecting things,\n"
    .string "even as a child!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
    .string "BILL files his own POKéMON data on\n"
    .string "his PC.\p"
    .string "Did he show you?$"

