CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon::
    .string "I found this most remarkable fossil\n"
    .string "inside MT. MOON.\p"
    .string "I think it's of a rare, prehistoric\n"
    .string "POKéMON.$"


CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pI thought he was a magnetic rock. He's actually just very clingy.\pWould you like to take this\nAlolan variant?"

CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton_DeclinedText::
    .string "Oh, okay. Maybe next time!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton_NoRoomText::
    .string "You've got no room in your party!"


CinnabarIsland_PokemonLab_Lounge_EventScript_Norma_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pHis neck is so long he keeps getting stuck in the ceiling fans.\pWould you like to take this\nAlolan variant?"

CinnabarIsland_PokemonLab_Lounge_EventScript_Norma_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Norma_DeclinedText::
    .string "Oh, okay. Maybe next time!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Norma_NoRoomText::
    .string "You've got no room in your party!"


CinnabarIsland_PokemonLab_Lounge_EventScript_Garett_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pHe's too busy fire-dancing to actually battle. It's a distraction.\pWould you like to take this\nAlolan variant?"

CinnabarIsland_PokemonLab_Lounge_EventScript_Garett_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Garett_DeclinedText::
    .string "Oh, okay. Maybe next time!"

CinnabarIsland_PokemonLab_Lounge_EventScript_Garett_NoRoomText::
    .string "You've got no room in your party!"

