VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
    .string "HRISHI: I'm usually at the GYM,\n"
    .string "but I love coming back to this\l"
    .string "safe haven in BURNOUT CITY.$"

VermilionCity_House3_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
    .string "Dear PIPPI,\n"
    .string "I hope to see you soon.\p"
    .string "I heard SAFFRON has problems with\n"
    .string "TEAM ROCKET.\p"
    .string "VERMILION appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
    .string "I want to exchange MAIL with all\n"
    .string "sorts of people.\p"
    .string "I send my PIDGEY to a UNION ROOM\n"
    .string "to exchange MAIL for me.$"

