VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
    .string "DAN: LIV and I love the sunset views\n"
    .string "from this harbor! It's the best\l"
    .string "place to relax after a long day.$"

VermilionCity_House1_Text_TakeThisAndFish::
    .string "LIV: Welcome to our home!\n"
    .string "DAN is usually out by the harbor,\n"
    .string "but I prefer the comfort of our\l"
    .string "cosy little house.$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
    .string "{PLAYER} received an OLD ROD from\n"
    .string "the FISHING GURU.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
    .string "Fishing is a way of life!\n"
    .string "It is like the finest poetry.\p"
    .string "From the seas to rivers, go out\n"
    .string "and land the big one, my friend.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
    .string "Oh…\n"
    .string "That's so disappointing…$"

VermilionCity_House1_Text_HowAreTheFishBiting::
    .string "Hello there, {PLAYER}!\p"
    .string "How are the fish biting?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
    .string "Oh, no!\p"
    .string "I had a nice gift for you, but you\n"
    .string "have no room for it!$"

