LavenderTown_Text_DoYouBelieveInGhosts::
    .string "DIVA: Do you believe in ghosts?\n"
    .string "Or are they just misunderstood fans?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "DIVA: Really?\n"
    .string "So there are believers… how cute.$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "DIVA: Hahaha, I guess not.\p"
    .string "That pale hand on your shoulder…\n"
    .string "It's probably just Edward.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "JORDI: This town is famous for its\n"
    .string "spooky vibes and ghost stories.\p"
    .string "It's the perfect place for a\n"
    .string "Masquerade, don't you think?$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "AMBER: Ghosts appeared in the TOWER.\p"
    .string "I heard TEAM ROCKET is holding a\n"
    .string "dog named FIG up there!\p"
    .string "They're probably planning to take\n"
    .string "her to their boss in STARRIDER CITY.$"

LavenderTown_Text_TownSign::
    .string "MASQUERADE TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "MASQUERADE VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_EdwardFan::
    .string "DIVA: Edward is so mysterious...\n"
    .string "just like the ghosts in the TOWER.\p"
    .string "I wish he would sparkle here!$"

LavenderTown_Text_JacobFan::
    .string "AMBER: Vampires? Pfft.\n"
    .string "Werewolves are way cooler.\p"
    .string "I'm heading to DIABLO ISLAND\n"
    .string "to find more Team Jacob fans!$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"

