LavenderTown_Text_DoYouBelieveInGhosts::
    .string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
    .string "Really?\n"
    .string "So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
    .string "Hahaha, I guess not.\p"
    .string "That white hand on your shoulder…\n"
    .string "I'm just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
    .string "This town is known as the grave\n"
    .string "site of POKéMON.\p"
    .string "Memorial services are held in\n"
    .string "POKéMON TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
    .string "Ghosts appeared in POKéMON TOWER.\p"
    .string "I heard TEAM ROCKET is holding a\n"
    .string "dog named FIG up there!\p"
    .string "They're probably planning to take\n"
    .string "her to their boss in SAFFRON-SWAN CITY.$"

LavenderTown_Text_TownSign::
    .string "LA-VAMPIRE TOWN\n"
    .string "The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
    .string "New SILPH SCOPE!\n"
    .string "Make the Invisible Plain to See!\p"
    .string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
    .string "LA-VAMPIRE VOLUNTEER\n"
    .string "POKéMON HOUSE$"

LavenderTown_Text_EdwardFan::
    .string "Edward is so mysterious... just\n"
    .string "like the ghosts in the TOWER.\p"
    .string "I wish he would sparkle here!$"

LavenderTown_Text_JacobFan::
    .string "Vampires? Pfft.\n"
    .string "Werewolves are way cooler.\p"
    .string "I'm heading to CINNA-BELLA ISLAND\n"
    .string "to find more Team Jacob fans!$"

LavenderTown_Text_PokemonTowerSign::
    .string "POKéMON TOWER\n"
    .string "Becalm the Spirits of POKéMON$"

