SaffronCity_Gym_Text_SabrinaIntro::
    .string "I had a vision of your arrival.\p"
    .string "I have had psychic powers since I\n"
    .string "was a child.\p"
    .string "I first learned to bend spoons with\n"
    .string "my mind.\p"
    .string "I dislike fighting, but if you wish,\n"
    .string "I will show you my powers!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

SaffronCity_Gym_Text_SabrinaDefeat::
    .string "I'm shocked!\n"
    .string "But, though I lost, I still have my\l"
    .string "psychic powers!\p"
    .string "You won the MARSHBADGE!$"

SaffronCity_Gym_Text_SabrinaNotEnoughMons::
    .string "BRYONY: Oh! You only have one\n"
    .string "POKéMON with you?\p"
    .string "FARIS: We only battle two-on-two.\n"
    .string "Come back when you have more!$"

SaffronCity_Gym_Text_SabrinaPostBattle::
    .string "Everyone has psychic power.\n"
    .string "People just don't realize it.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
    .string "The MARSHBADGE makes POKéMON up\n"
    .string "to Lv. 70 obey you.\p"
    .string "Stronger POKéMON will become wild,\n"
    .string "ignoring your orders in battle.\p"
    .string "Just don't raise your POKéMON too\n"
    .string "much to avoid that problem.\p"
    .string "Wait, please take this TM with you.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
    .string "{PLAYER} received TM04 from\n"
    .string "SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
    .string "TM04 is CALM MIND.\p"
    .string "It makes the POKéMON concentrate\n"
    .string "to raise both SP. ATK and SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
    .string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
    .string "SABRINA is far younger than I,\n"
    .string "but she has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
    .string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
    .string "In a battle of equals, the one\n"
    .string "with the stronger will wins.\p"
    .string "If you wish to beat SABRINA, focus\n"
    .string "and will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
    .string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
    .string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
    .string "PSYCHIC POKéMON fear only ghosts\n"
    .string "and bugs!$"

SaffronCity_Gym_Text_StacyIntro::
    .string "POKéMON take on the appearance of\n"
    .string "their TRAINERS.\p"
    .string "Your POKéMON must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
    .string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
    .string "I have much to learn still…\p"
    .string "I must master PSYCHIC and teach it\n"
    .string "to my POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
    .string "You understand, don't you?\p"
    .string "That power alone isn't enough to\n"
    .string "win in the world of POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
    .string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
    .string "SABRINA just wiped out the KARATE\n"
    .string "MASTER next door.$"

SaffronCity_Gym_Text_TashaIntro::
    .string "You and I, our POKéMON shall\n"
    .string "battle!$"

SaffronCity_Gym_Text_TashaDefeat::
    .string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
    .string "I knew that this was going to take\n"
    .string "place.$"

SaffronCity_Gym_Text_CameronIntro::
    .string "SABRINA is young, but she's also\n"
    .string "our highly skilled LEADER.\p"
    .string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
    .string "Ow!\n"
    .string "Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
    .string "There used to be two POKéMON GYMS\n"
    .string "in SAFFRON.\p"
    .string "The FIGHTING DOJO next door lost\n"
    .string "its GYM status, though.\p"
    .string "We simply creamed them when we\n"
    .string "decided to have just one GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
    .string "SAFFRON POKéMON GYM is famous for\n"
    .string "training psychics.\p"
    .string "You want to see SABRINA, don't\n"
    .string "you? I can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
    .string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
    .string "That's right! I used telepathy to\n"
    .string "read your mind!$"

CeruleanCity_Gym_Text_OllieIntro::
    .string "OLLIE: Hey SHUKTI! You're almost\n"
    .string "there. Just a few more badges!\p"
    .string "I've got a little something for you.\n"
    .string "A ball for a true friend.$"

SaffronCity_Gym_Text_OllieGiftSaffron::
    .string "OLLIE: Here, take this.$"

SaffronCity_Gym_Text_OllieAdvice::
    .string "OLLIE: They use a lot of Psychic\n"
    .string "types here. You've got this!\p"
    .string "Every badge you get makes me more\n"
    .string "excited for when we're finally\l"
    .string "reunited at the finish line.$"

SaffronCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: You did it! SABRINA was\n"
    .string "no match for your bond.\p"
    .string "I'm heading to my final stop now.\n"
    .string "I'll be waiting for you!$"

SaffronCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

SaffronCity_Gym_Text_GymStatue::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
    .string "SAFFRON POKéMON GYM\n"
    .string "LEADER: SABRINA\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

