PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
    .string "A shady old guy sucked me into\n"
    .string "buying this weird fish POKéMON!\p"
    .string "It's totally weak and it cost ¥500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
    .string "Good things can happen if you raise\n"
    .string "POKéMON diligently.\p"
    .string "Even the weak ones can surprise\n"
    .string "you if you don't give up on them.$"

PewterCity_Mart_Text_PokeASDA_AuditStep1::
    .string "Oh, you're the Mystery Shopper!\p"
    .string "I hope our stock of ESCAPE ROPES\n"
    .string "is up to the corporate standard.\p"
    .string "Please continue your audit at\n"
    .string "our POOLSIDE CITY branch.$"

