CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
    .string "Me?\n"
    .string "I’m OLLIE, the technical director!\p"
    .string "I’m the one who fixed the black\n"
    .string "screen bug and automated the intro.\l"
    .string "Anything for the boss of\l"
    .string "The Sweet Spot!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
    .string "I’m OLLIE, the stylist!\p"
    .string "I’m the one who picked the Danger\n"
    .string "Jones palette for the cities.\l"
    .string "ADRENALINE CITY looks much\l"
    .string "better in neon green, don't you think?$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
    .string "I’m OLLIE, the writer!\p"
    .string "Every word in this game is a love\n"
    .string "letter to SHUKTI.\p"
    .string "I hope you're having the best\n"
    .string "birthday ever!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
    .string "Is that right?\p"
    .string "I’m OLLIE, the lead designer!\p"
    .string "I spent weeks hacking this world\n"
    .string "just to make sure your birthday\l"
    .string "was perfect.\p"
    .string "You look great in these pixels,\n"
    .string "SHUKTI!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
    .string "Wow! Excellent!\n"
    .string "You completed the POKéDEX I built!\l"
    .string "Congratulations, baby!\l"
    .string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
    .string "It’s the game program! OLLIE's\n"
    .string "hard work is stored here.$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
    .string "OLLIE is taking a break to watch\n"
    .string "Heated Rivalry! Go Hockey!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
    .string "It’s the script for SHUKTI's game!\n"
    .string "The ending is full of spoilers!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
    .string "OLLIE'S Development Suite$"

