ViridianCity_Gym_Text_ZaynabIntro::
    .string "ZAYNAB: SHUKTI! You finally made it!\p"
    .string "We heard about GIOVANNI's evil plans\n"
    .string "and couldn't let him stay in our\l"
    .string "local gym any longer.\p"
    .string "We teamed up and kicked him out\n"
    .string "ourselves!\p"
    .string "But now, to get to the POKéMON LEAGUE,\n"
    .string "you'll have to prove you're stronger\l"
    .string "than both of us together!$"

ViridianCity_Gym_Text_ZaynabDefeat::
    .string "Unbelievable!\n"
    .string "You really are the best of us.\p"
    .string "As proof, here is the EARTHBADGE!\n"
    .string "{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_ZaynabPostBattle::
    .string "ZAYNAB: You've got what it takes,\n"
    .string "SHUKTI. Go show OLLIE what you're\l"
    .string "made of at the Plateau!$"

ViridianCity_Gym_Text_AliyahIntro::
    .string "ALIYAH: GIOVANNI was tough, but\n"
    .string "working together, we were tougher.\p"
    .string "Don't expect us to go easy on you\n"
    .string "just because we're friends!$"

ViridianCity_Gym_Text_AliyahPostBattle::
    .string "ALIYAH: Wow, SHUKTI! That was\n"
    .string "incredible. You've really grown\l"
    .string "as a Trainer.$"

ViridianCity_Gym_Text_ZaynabNotEnoughMons::
    .string "ZAYNAB: You need at least two\n"
    .string "POKéMON to battle us together!$"

ViridianCity_Gym_Text_ReceivedTM26FromZaynab::
    .string "{PLAYER} received TM26\n"
    .string "from ZAYNAB and ALIYAH.$"

ViridianCity_Gym_Text_OllieIntro::
    .string "OLLIE: Hey SHUKTI! The final badge.\n"
    .string "You've come so far. I'm so proud.\p"
    .string "I've got a final gift for you.\n"
    .string "Five tokens of my love.$"

ViridianCity_Gym_Text_OllieGiftViridian::
    .string "OLLIE: Here, take these.$"

ViridianCity_Gym_Text_OllieAdvice::
    .string "OLLIE: ZAYNAB and ALIYAH are\n"
    .string "an incredible team. But I know\l"
    .string "you're ready.\p"
    .string "I've secured a very special spot\n"
    .string "for us to meet once you've won.\l"
    .string "I'll be waiting with open arms.$"

ViridianCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: Blow me away! You beat them!\p"
    .string "It's time, SHUKTI. Head to IN-DYE-GO PLATEAU.\n"
    .string "I'll be there, waiting for our\l"
    .string "final date.$"

ViridianCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto these for you.$"

ViridianCity_Gym_Text_GymStatue::
    .string "VIRID-LAN CITY POKéMON GYM\n"
    .string "LEADERS: ZAYNAB & ALIYAH\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
    .string "VIRID-LAN CITY POKéMON GYM\n"
    .string "LEADERS: ZAYNAB & ALIYAH\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

