Route2_House_Text_FaintedMonsCanUseFieldMoves::
    .string "A fainted POKéMON just has no\n"
    .string "energy left to battle.\p"
    .string "It can still use moves like CUT\n"
    .string "outside of battle.$"


Route2_House_EventScript_Reyley_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pHe kept eating all my expensive imported malasadas!\pWould you like to take this\nAlolan variant?"

Route2_House_EventScript_Reyley_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

Route2_House_EventScript_Reyley_DeclinedText::
    .string "Oh, okay. Maybe next time!"

Route2_House_EventScript_Reyley_NoRoomText::
    .string "You've got no room in your party!"

