CeruleanCity_House2_Text_RocketsStoleTMForDig::
    .string "BRANDON: This city has such a cool\n"
    .string "vibe! HANNAH and I are so glad we\l"
    .string "moved here to be close to the gym.$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
    .string "HANNAH: Welcome to our home!\n"
    .string "BRANDON is usually at the gym,\n"
    .string "but I prefer the comfort of our\l"
    .string "little Poolside sanctuary.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
    .string "TEAM ROCKET must be trying to DIG\n"
    .string "their way into no good!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
    .string "TEAM ROCKET left a way out!$"

