LavenderTown_House1_Text_Cubone::
    .string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
    .string "Those horrible ROCKETS!\n"
    .string "They deserve no mercy!\p"
    .string "That poor CUBONE's mother…\p"
    .string "It was killed trying to escape from\n"
    .string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
    .string "The ghost of POKéMON TOWER is\n"
    .string "gone!\p"
    .string "Someone must have soothed its\n"
    .string "restless spirit!$"

LavenderTown_House1_Text_StaceyIntro::
    .string "STACEY: You again?!\p"
    .string "The bakery? Oh, that was a tax\n"
    .string "write-off. It's gone.\p"
    .string "Now I'm running a premium spiritual\n"
    .string "consultancy.\p"
    .string "This CUBONE is clearly suffering\n"
    .string "from blocked chakras.\p"
    .string "I'm selling 'Karma Cleanse' tags.\n"
    .string "Here, take one. First one's free.$"

LavenderTown_House1_Text_StaceyGivenTag::
    .string "STACEY: That will keep the bad\n"
    .string "vibes away. Probably.$"

LavenderTown_House1_Text_StaceyPostTag::
    .string "STACEY: If this doesn't work out,\n"
    .string "I hear there's money in zoos...$"

