SaffronCity_House_Text_Janhvi::
    .string "JANHVI: JUSTIN and I love the energy\n"
    .string "of this city! There's always\l"
    .string "something new to discover in\l"
    .string "STARRIDER CITY.$"

SaffronCity_House_Text_Justin::
    .string "JUSTIN: Welcome! I'm always looking\n"
    .string "for the next big media event.\l"
    .string "JANHVI says I should relax more,\l"
    .string "but where's the fun in that?$"

SaffronCity_House_Text_Pidgey::
    .string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_ExplainPPUp::
    .string "I was given a PP UP as a gift.\p"
    .string "It's used to increase the PP of\n"
    .string "a POKéMON's move.\p"
    .string "I should use it on a powerful move\n"
    .string "with only a few PP.$"
