FuchsiaCity_PokemonCenter_1F_Text_ProfTree_Intro::
    .string "TREE: Ah, {PLAYER}!\n"
    .string "You've made it all the way to\l"
    .string "FO-SHEAR-IA CITY!\p"
    .string "I have the final one of my special\n"
    .string "starter POKéMON with me.\p"
    .string "Since you've come so far, I want\n"
    .string "you to have it!$"

FuchsiaCity_PokemonCenter_1F_Text_ProfTree_Outro::
    .string "TREE: Now you have all three of\n"
    .string "my original starters!\p"
    .string "You are truly a remarkable Trainer.\n"
    .string "Go forth and conquer the League!$"

FuchsiaCity_PokemonCenter_1F_Text_ProfTree_AlreadyGot::
    .string "TREE: Take good care of those\n"
    .string "POKéMON. They are very dear to me.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "VIRID-LAN CITY.\p"
    .string "It goes to the POKéMON LEAGUE HQ.\n"
    .string "The HQ governs all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a POKéDEX,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare POKéMON breed\n"
    .string "there.$"

