CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
    .string "STEVE: This city has such a cool\n"
    .string "aura! FERNANDA and I are so\l"
    .string "glad we moved here.$"

CeruleanCity_House1_Text_DescribeWhichBadge::
    .string "FERNANDA: I love our little house\n"
    .string "by the pool! It's so peaceful\l"
    .string "when STEVE isn't talking about\l"
    .string "his latest Pokémon catch.$"

CeruleanCity_House1_Text_ComeVisitAnytime::
    .string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
    .string "The ATTACK stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLASH outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
    .string "POKéMON up to Lv. 30 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "CUT outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly::
    .string "The SPEED stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "FLY outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
    .string "POKéMON up to Lv. 50 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "STRENGTH outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
    .string "The DEFENSE stat of all your\n"
    .string "POKéMON increases a little bit.\p"
    .string "It also lets you use the move\n"
    .string "SURF outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
    .string "POKéMON up to Lv. 70 will obey\n"
    .string "you.\p"
    .string "That includes even outsiders you\n"
    .string "obtain in trades.\p"
    .string "POKéMON of higher levels will\n"
    .string "be unruly in battle, however.\p"
    .string "It also lets you use the move\n"
    .string "ROCK SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
    .string "The SP. ATK and SP. DEF stats of\n"
    .string "all your POKéMON rise a little bit.\p"
    .string "It also lets you use the move\n"
    .string "WATERFALL outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
    .string "All POKéMON will obey you!$"

