CeruleanCity_Gym_Text_MistyIntro::
    .string "SOMEBODY ONCE TOLD ME YOU WANT TO\n"
    .string "BATTLE BRYONY! Aare you ready?\l"
    .string "Let's do this!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "It's a great move for all sorts\n"
    .string "of POKéMON!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.$"

CeruleanCity_Gym_Text_BryonyPostBattleBeatBowie::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.\p"
    .string "Oh, you already beat him!$"

CeruleanCity_Gym_Text_BryonyPostBattleCaughtBowie::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.\p"
    .string "Wait... you CAUGHT HIM!?$"

CeruleanCity_Gym_Text_BowieIntro::
    .string "BOWIE: Woof!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "BRYONY is the best! She's so much\n"
    .string "more fun than MISTY was.$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "BRYONY and BOWIE are a legendary\n"
    .string "duo here in LETCHWORTH!$"

CeruleanCity_Gym_Text_OllieIntro::
    .string "OLLIE: Hey SHUKTI! This gym is full\n"
    .string "of surprises, isn't it?\p"
    .string "I've got a little something sweet\n"
    .string "for you. Just like you.$"

CeruleanCity_Gym_Text_OllieGiftCerulean::
    .string "OLLIE: Here, take this.$"

CeruleanCity_Gym_Text_OllieAdvice::
    .string "OLLIE: BRYONY uses her favorites.\n"
    .string "She's tough, but she doesn't know\l"
    .string "that I'm always one step ahead.\p"
    .string "I'm making sure everything is\n"
    .string "perfect for our final meeting.$"

CeruleanCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: You beat BRYONY! That was\n"
    .string "an incredible match!\p"
    .string "You're getting closer to me with\n"
    .string "every step. I can't wait.$"

CeruleanCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

CeruleanCity_Gym_Text_GymStatue::
    .string "LETCHWORTH POKéMON GYM\n"
    .string "LEADER: BRYONY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "LETCHWORTH POKéMON GYM\n"
    .string "LEADER: BRYONY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

