CeruleanCity_Gym_Text_MistyIntro::
    .string "SOMEBODY ONCE TOLD ME YOU WANT TO\n"
    .string "BATTLE BRYONY! Aare you ready?\l"
    .string "Let's do this!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

CeruleanCity_Gym_Text_ExplainTM03::
    .string "TM03 teaches WATER PULSE.\p"
    .string "It's a great move for all sorts\n"
    .string "of POKéMON!$"

CeruleanCity_Gym_Text_MistyDefeat::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.$"

CeruleanCity_Gym_Text_BryonyPostBattleBeatBowie::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.\p"
    .string "Oh, you already beat him!$"

CeruleanCity_Gym_Text_BryonyPostBattleCaughtBowie::
    .string "Bugger, I knew I should have just\n"
    .string "sent Bowie out to battle instead.\p"
    .string "You beat me fair and square!\p"
    .string "Take this to prove what a great\n"
    .string "hair wizard and trainer you are.\p"
    .string "Wait... you CAUGHT HIM!?$"

CeruleanCity_Gym_Text_BowieIntro::
    .string "BOWIE: Woof!$"

CeruleanCity_Gym_Text_DianaPostBattle::
    .string "BRYONY is the best! She's so much\n"
    .string "more fun than MISTY was.$"

CeruleanCity_Gym_Text_LuisPostBattle::
    .string "BRYONY and BOWIE are a legendary\n"
    .string "duo here in POOLSIDE CITY!$"

CeruleanCity_Gym_Text_OllieIntro::
    .string "OLLIE: You look amazing today,\n"
    .string "SHUKTI. The journey suits you.\p"
    .string "I've got a little something sweet\n"
    .string "for you. Just like you.$"

CeruleanCity_Gym_Text_OllieGiftCerulean::
    .string "OLLIE: Here, take this.$"

CeruleanCity_Gym_Text_OllieAdvice::
    .string "OLLIE: BRYONY doesn't stick to one\n"
    .string "type, she uses what she loves.\p"
    .string "Be ready for anything! I'm actually\n"
    .string "scouting out the path ahead for us.\l"
    .string "See you soon!$"

CeruleanCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: You beat BRYONY! That was\n"
    .string "an incredible match!\p"
    .string "You're getting stronger so fast.\n"
    .string "I better work hard too, just to\l"
    .string "keep up with you!$"

CeruleanCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

CeruleanCity_Gym_Text_GymStatue::
    .string "POOLSIDE CITY POKéMON GYM\n"
    .string "LEADER: BRYONY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
    .string "POOLSIDE CITY POKéMON GYM\n"
    .string "LEADER: BRYONY\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
    .string "The CASCADEBADGE makes all POKéMON\n"
    .string "up to Lv. 30 obey you.\p"
    .string "That includes even those you got\n"
    .string "through trades.\p"
    .string "It also lets you use CUT outside\n"
    .string "of battle.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
    .string "{PLAYER} received TM03 from BRYONY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
    .string "You'd better make room for this!$"

