FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
    .string "Hello! I am the STYLE CONSULTANT.\p"
    .string "I help POKéMON 'cut' old, out-of-fashion\n"
    .string "moves to keep their palette fresh.\p"
    .string "Need a trim?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
    .string "Which POKéMON needs a move\n"
    .string "trimmed?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
    .string "Which move should we cut?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
    .string "{STR_VAR_1} only has one move left!\n"
    .string "We can't cut that!$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
    .string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
    .string "You want to trim that move?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
    .string "A perfect cut!\p"
    .string "{STR_VAR_1} has forgotten\n"
    .string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
    .string "Come back if your POKéMON needs\n"
    .string "another style adjustment.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
    .string "What?\n"
    .string "No EGG should know any moves.$"

