Text_DreamEaterTeach::
    .string "Yawn!\n"
    .string "I must have dozed off in the sun.\p"
    .string "I had this weird dream about\n"
    .string "a DROWZEE eating my dream.\p"
    .string "And…\n"
    .string "I learned how to eat dreams…\p"
    .string "Oogh, this is too spooky!\p"
    .string "Let me teach it to a POKéMON so\n"
    .string "I can forget about it!$"

Text_DreamEaterDeclined::
    .string "…Snore…$"

Text_DreamEaterWhichMon::
    .string "Which POKéMON wants to learn\n"
    .string "DREAM EATER?$"

Text_DreamEaterTaught::
    .string "…ZZZ…\n"
    .string "I…can't eat…anymore…$"

PewterCity_Text_ClefairyCameFromMoon::
    .string "JANE: Hey! Did you know CLEFAIRY\n"
    .string "actually came from the moon?\p"
    .string "It's way cooler than those boring\n"
    .string "fossils in the museum!$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
    .string "JOHN: Looking for a real fight?\n"
    .string "Most people here just catch bugs.\p"
    .string "But FARIS? He's the real deal.\n"
    .string "His POKéMON are as tough as the\l"
    .string "pavement in this city!$"

PewterCity_Text_DidYouCheckOutMuseum::
    .string "CAROLYN: Did you check out the\n"
    .string "MUSEUM? It's pretty cool!\p"
    .string "Some Rocket thugs were here earlier\n"
    .string "trying to 'fossilize' a shiny dog.\l"
    .string "But she was too cute to stay still!\p"
    .string "I think they headed east to\n"
    .string "POOLSIDE CITY.$"

PewterCity_Text_WerentThoseFossilsAmazing::
    .string "CAROLYN: Those fossils from\n"
    .string "MT. MOON are amazing, right?$"

PewterCity_Text_ReallyYouHaveToGo::
    .string "CAROLYN: Seriously?\n"
    .string "You absolutely have to go see them!$"

PewterCity_Text_ThisIsTheMuseum::
    .string "CAROLYN: This is the MUSEUM.\p"
    .string "It costs a bit to get in, but it's\n"
    .string "worth every yen. See ya!$"

PewterCity_Text_DoYouKnowWhatImDoing::
    .string "Psssst!\n"
    .string "Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
    .string "That's right!\n"
    .string "It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
    .string "I'm spraying REPEL to keep wild\n"
    .string "POKéMON out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
    .string "JOHN: You're a TRAINER, right?\p"
    .string "FARIS is looking for fresh blood.\n"
    .string "Follow me to the GYM!$"

PewterCity_Text_GoTakeOnBrock::
    .string "JOHN: If you think you're ready,\n"
    .string "go take on FARIS!$"

PewterCity_Text_TrainerTipsEarningEXP::
    .string "TRAINER TIPS\p"
    .string "Every second your POKéMON is in\n"
    .string "battle, it's learning. Gain that EXP!$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
    .string "NOTICE!\p"
    .string "Thieves have been stealing POKéMON\n"
    .string "fossils from MT. MOON.\p"
    .string "Please call the PAVEMENT POLICE if\n"
    .string "you have any information.$"

PewterCity_Text_MuseumOfScience::
    .string "PAVEMENT MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
    .string "PAVEMENT CITY POKéMON GYM\n"
    .string "LEADER: FARIS\l"
    .string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_CitySign::
    .string "PAVEMENT CITY\n"
    .string "A Stone Gray City$"

@ The below 3 JP texts are unused. Possibly a cut NPC meant to give the player the Berry Pouch
PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
    .string "あッれー！\n"
    .string "その　ジムバッジ‥‥\l"
    .string "すげえな　タケシに　かったのかよ！\p"
    .string "かんどう　したから\n"
    .string "おれの　たからもの　やるよ！$"

PewterCity_Text_BerriesInsideUseCarefully::
    .string "なかには　きのみが　はいってるぜ\p"
    .string "やくに　たつ　きのみも\n"
    .string "はいって　いるから\l"
    .string "だいじに　つかって　くれよ！$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
    .string "ポケモンに　きのみを\n"
    .string "もたせて　おけば\l"
    .string "たたかっている　ときに\l"
    .string "かってに　つかって　くれるんだ\p"
    .string "キズぐすり　とか　どくけし　より\n"
    .string "てがるで　べんり　だろ？$"

PewterCity_Text_OhPlayer::
    .string "Oh, {PLAYER}!$"

PewterCity_Text_AskedToDeliverThis::
    .string "I'm glad I caught up to you.\n"
    .string "I'm PROF. TREE's AIDE.\p"
    .string "I've been asked to deliver this\n"
    .string "from NIKY, so here you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
    .string "{PLAYER} received the\n"
    .string "RUNNING SHOES from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
    .string "{PLAYER} switched shoes with the\n"
    .string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
    .string "Press the B Button to run.\n"
    .string "Now you can chase after STACEY!$"

PewterCity_Text_MustBeGoingBackToLab::
    .string "Well, I must be going back to\n"
    .string "the LAB.\p"
    .string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
    .string "There's a letter attached…\p"
    .string "Dear {PLAYER},\p"
    .string "Here is a pair of RUNNING SHOES\n"
    .string "for my beloved Champion.\p"
    .string "Remember, I'll always be cheering\n"
    .string "for you while I watch the hockey!\p"
    .string "Love, Niky$"

