Route18_EastEntrance_2F_Text_PalletTownInWest::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "CLEAR TOWN is in the west.$"

Route18_EastEntrance_2F_Text_PeopleSwimming::
    .string "Let's see what the binoculars have\n"
    .string "to show…\p"
    .string "There are people swimming.$"


Route18_EastEntrance_2F_EventScript_Haden_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pHe actually smells like a tropical vacation... but in a really confusing way.\pWould you like to take this\nAlolan variant?"

Route18_EastEntrance_2F_EventScript_Haden_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

Route18_EastEntrance_2F_EventScript_Haden_DeclinedText::
    .string "Oh, okay. Maybe next time!"

Route18_EastEntrance_2F_EventScript_Haden_NoRoomText::
    .string "You've got no room in your party!"

