CeladonCity_House1_Text_SlotsReelInTheDough::
    .string "ASHLEY: I love the rainbow vibes of\n"
    .string "this city! MATT and I are so lucky\l"
    .string "to live here.$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
    .string "MATT: This city is so luxurious!\n"
    .string "I just hope poor FIG is safe somewhere\l"
    .string "nearby. I've been keeping a look out.$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
    .string "Don't touch the poster at the GAME\n"
    .string "CORNER!\p"
    .string "There's no secret switch behind it!$"

@ Text for the replaced altars in the rocket chiefs house / celadon mansion
@ In English RB, this is westernized as "It's a sculpture of DIGLETT.", and is removed altogether in FRLG
Text_ItsABuddhistAltar::
    .string "ぶつだん　だ‥$"
