ViridianCity_School_Text_TryingToMemorizeNotes::
    .string "Whew! I'm trying to memorize all these\n"
    .string "tax avoidance strategies.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
    .string "Okay!\p"
    .string "Be sure to read the board carefully!\n"
    .string "Some students here... like STACEY...\l"
    .string "really struggle with basic logic.$"

ViridianCity_School_Text_StaceyIntro::
    .string "STACEY: Ugh, {PLAYER}!?\n"
    .string "Don't look at me!\p"
    .string "That mean investigator DAISY sent\n"
    .string "me here to 're-educate' me on\l"
    .string "proper business practices.\p"
    .string "As if I don't know how to run a\n"
    .string "salon! Redundancies are a perfectly\l"
    .string "valid strategy!$"

ViridianCity_School_Text_NotebookFirstPage::
    .string "It's a business ledger.\p"
    .string "First page…\p"
    .string "Revenue - Expenses = Profit.\p"
    .string "If Profit < 0, fire everyone and\n"
    .string "call it 'strategic restructuring'.$"

ViridianCity_School_Text_NotebookSecondPage::
    .string "Second page…\p"
    .string "A healthy business avoids taxes.\n"
    .string "Use offshore accounts to weaken\l"
    .string "the tax man's resolve.$"

ViridianCity_School_Text_NotebookThirdPage::
    .string "Third page…\p"
    .string "Business owners seek others to\n"
    .string "engage in hostile takeovers.\p"
    .string "To CEOs, the taste of a monopoly\n"
    .string "is sweet, indeed.$"

ViridianCity_School_Text_NotebookFourthPage::
    .string "Fourth page…\p"
    .string "The ultimate goal for all business\n"
    .string "owners is simple.\p"
    .string "It is to defeat the top eight\n"
    .string "regulatory bodies.\p"
    .string "Do so to earn the right to face…\p"
    .string "The SUPREME COURT of the\n"
    .string "PokeASDA LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
    .string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
    .string "GIRL: Hey!\n"
    .string "Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
    .string "The blackboard lists POKéMON\n"
    .string "STATUS problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
    .string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
    .string "A POKéMON can't attack if it's\n"
    .string "asleep.\p"
    .string "POKéMON will stay asleep even\n"
    .string "after battles.\p"
    .string "Use AWAKENING to awaken one\n"
    .string "from sleep.$"

ViridianCity_School_Text_ExplainBurn::
    .string "A burn reduces ATTACK power.\n"
    .string "It also causes ongoing HP loss.\p"
    .string "A burn remains after a battle.\n"
    .string "Use BURN HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
    .string "When poisoned, a POKéMON's health\n"
    .string "steadily drops.\p"
    .string "Poison lingers after battles.\n"
    .string "Use an ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
    .string "A frozen POKéMON becomes\n"
    .string "helplessly immobile.\p"
    .string "It stays frozen even after the\n"
    .string "battle ends.\p"
    .string "Use ICE HEAL to thaw out the\n"
    .string "suffering POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
    .string "Paralysis reduces SPEED and may\n"
    .string "prevent the POKéMON from moving.\p"
    .string "Paralysis remains after battles.\n"
    .string "Use PARLYZ HEAL for treatment.$"

