PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
    .string "NIKY: …{PLAYER}.\n"
    .string "I'm so proud of the trainer you're\l"
    .string "becoming! Just remember to take\l"
    .string "a break every now and then.\p"
    .string "Oh, yes. PROF. TREE, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
    .string "NIKY: …{PLAYER}.\n"
    .string "I'm so proud of the trainer you're\l"
    .string "becoming! Just remember to take\l"
    .string "a break every now and then.\p"
    .string "Oh, yes. PROF. TREE, next door, was\n"
    .string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
    .string "NIKY: {PLAYER}!\n"
    .string "You look exhausted. Take a quick\l"
    .string "rest, baby.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
    .string "NIKY: There! You and your POKéMON\n"
    .string "look refreshed. Go show them what\l"
    .string "you've got!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
    .string "Heated rivalry is on!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
    .string "Heated rivalry is on!$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
    .string "Oops, wrong side…$"

PalletTown_PlayersHouse_1F_Text_Gary::
    .string "GARY: Go get 'em, champ! NIKY and I\n"
    .string "are behind you 100%.\p"
    .string "We know you're going to make us\n"
    .string "all so proud!$"
