LavenderTown_House2_Text_WantMeToRateNicknames::
    .string "Hello! I am the professional\n"
    .string "BRAND MANAGER!\p"
    .string "Want me to see if your POKéMON's\n"
    .string "name fits our professional vibe?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
    .string "Which POKéMON needs a brand\n"
    .string "audit?$"

LavenderTown_House2_Text_GiveItANicerName::
    .string "{STR_VAR_1}, is it?\n"
    .string "That's a decent enough name.\p"
    .string "But, would you like me to help you\n"
    .string "rebrand it into something bolder?\p"
    .string "How about it?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
    .string "Excellent. What shall the new\n"
    .string "brand name be?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
    .string "Perfect! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "It fits the professional palette\n"
    .string "so much better!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
    .string "I see. Keep your brands consistent!$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
    .string "Done! From now on, this POKéMON\n"
    .string "shall be known as {STR_VAR_1}!\p"
    .string "The name is the same, but the vibe\n"
    .string "is vastly superior!$"

LavenderTown_House2_Text_TrulyImpeccableName::
    .string "{STR_VAR_1}, is it?\n"
    .string "That is a truly impeccable brand!\p"
    .string "It's pure quality. Perfect!$"


LavenderTown_House2_Text_ThatIsMerelyAnEgg::
    .string "Now, now.\n"
    .string "That is merely an EGG!$"

