CeruleanCity_Text_RivalIntro::
    .string "{RIVAL}: Yo! {PLAYER}!\p"
    .string "You're still struggling along back\n"
    .string "here?\p"
    .string "I'm doing great! I caught a bunch\n"
    .string "of strong and smart POKéMON!\p"
    .string "Here, let me see what you caught,\n"
    .string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
    .string "Hey!\n"
    .string "Take it easy!\l"
    .string "You won already!$"

CeruleanCity_Text_RivalPostBattle::
    .string "{RIVAL}: Hey, guess what?\p"
    .string "I went to BILL's and got him to\n"
    .string "show me his rare POKéMON.\p"
    .string "That added a lot of pages to my\n"
    .string "POKéDEX!\p"
    .string "After all, BILL's world famous as a\n"
    .string "POKéMANIAC.\p"
    .string "He invented the POKéMON Storage\n"
    .string "System on PC, too.\p"
    .string "Since you're using his system,\n"
    .string "you should go thank him.\p"
    .string "Well, I better get rolling!\n"
    .string "Smell ya later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
    .string "Oh, yeah, right.\p"
    .string "I feel sorry for you. No, really.\n"
    .string "You're always plodding behind me.\p"
    .string "So here, I'll give you a little\n"
    .string "present as a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
    .string "A chatty gossip like you…\n"
    .string "That thing's perfect.\p"
    .string "I don't need it because I don't\n"
    .string "give a hoot about others.\p"
    .string "All right, this time I really am\n"
    .string "gone. Smell ya!$"

@ RB translation: "Heh! You're no match for my genius!"
CeruleanCity_Text_RivalVictory::
    .string "なんたって！\n"
    .string "おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
    .string "Hey! Stay out!\n"
    .string "It's not your yard!\p"
    .string "I don't have the dog! STACEY told\n"
    .string "me to leave her at the warehouse\l"
    .string "in EMPIRE CITY!\p"
    .string "I'm just a redundant Grunt!{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
    .string "GRUNT: Stop! I give up!\n"
    .string "I'll leave quietly!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
    .string "…Okay.\n"
    .string "I'll return the TM I stole.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
    .string "{PLAYER} recovered TM28 from\n"
    .string "the TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye::
    .string "I better get moving!\n"
    .string "Bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
    .string "Make room for this!\n"
    .string "I can't run until I give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
    .string "MILAN: You're a TRAINER, too?\p"
    .string "Collecting, battling… it's a tough\n"
    .string "life, isn't it? I'd rather be\l"
    .string "somewhere cooler, honestly.$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
    .string "MILAN: Did you know that you can\n"
    .string "CUT down small trees?\p"
    .string "Even that small tree in front of\n"
    .string "STACEY's bakery can be CUT down.\p"
    .string "It might actually improve the\n"
    .string "decor, haha!$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
    .string "MILAN: If that SLOWBRO wasn't there,\n"
    .string "you could CUT down the small tree.\p"
    .string "It's always the slow ones blocking\n"
    .string "the progress, right?$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
    .string "CAROLYN: You're making an encyclopedia\n"
    .string "on POKéMON? That sounds like a lot\l"
    .string "of research. Good luck with that!$"

CeruleanCity_Text_PeopleHereWereRobbed::
    .string "The people here were robbed.\p"
    .string "It's obvious that TEAM ROCKET is\n"
    .string "behind this most heinous crime!\p"
    .string "I hope they didn't take any of\n"
    .string "the Liquid Death from the Mart!$"

CeruleanCity_Text_SlowbroUseSonicboom::
    .string "HRISHI: Okay! SLOWBRO!\n"
    .string "Execute optimized SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
    .string "HRISHI: Come on, SLOWBRO, increase\n"
    .string "your focus metrics!$"

CeruleanCity_Text_SlowbroPunch::
    .string "HRISHI: SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
    .string "HRISHI: No!\n"
    .string "Sub-optimal performance!$"

CeruleanCity_Text_SlowbroWithdraw::
    .string "HRISHI: SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
    .string "HRISHI: No! That's wrong!\n"
    .string "It's so hard to debug POKéMON!\p"
    .string "Your POKéMON's obedience depends\n"
    .string "on your Trainer API stability.$"

CeruleanCity_Text_SlowbroTookSnooze::
    .string "SLOWBRO entered sleep mode…$"

CeruleanCity_Text_SlowbroLoafingAround::
    .string "SLOWBRO is idling…$"

CeruleanCity_Text_SlowbroTurnedAway::
    .string "SLOWBRO dropped the connection…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
    .string "SLOWBRO ignored the command…$"

CeruleanCity_Text_WantBrightRedBicycle::
    .string "HANNAH: I want a bright red bicycle.\p"
    .string "I'll keep it at home, so it won't\n"
    .string "get dirty while I'm out partying!$"

CeruleanCity_Text_ThisIsCeruleanCave::
    .string "This is POOLSIDE CAVE.\p"
    .string "Horribly strong POKéMON live inside\n"
    .string "there.\p"
    .string "Only a Champion could handle the\n"
    .string "chaos inside. Are you strong\l"
    .string "enough, SHUKTI?$"

CeruleanCity_Text_CitySign::
    .string "POOLSIDE CITY\n"
    .string "A Mysterious, Blue Aura Surrounds\l"
    .string "It$"

CeruleanCity_Text_TrainerTipsHeldItems::
    .string "TRAINER TIPS\p"
    .string "A POKéMON can hold an item.\n"
    .string "Try giving one some Liquid Death!\l"
    .string "(Actually, don't, they'll just spill it.)$"

CeruleanCity_Text_BikeShopSign::
    .string "Handle grass and caves easily!\n"
    .string "BIKE SHOP$"

CeruleanCity_Text_GymSign::
    .string "POOLSIDE CITY POKéMON GYM\n"
    .string "LEADER: BRYONY\l"
    .string "The Tomboyish Mermaid!$"

