Route6_UnusedHouse_Text_Surprise::
	.string "EVERYONE: SURPRISE! HAPPY BIRTHDAY
"
	.string "SHUKTI!!!$"

Route6_UnusedHouse_Text_Claire::
	.string "CLAIRE: I knew you could do it!
"
	.string "Champion and another year older!$"

Route6_UnusedHouse_Text_Steve::
	.string "STEVE: Best birthday ever, right?
"
	.string "The whole of KANTO is celebrating!$"

Route6_UnusedHouse_Text_Fernanda::
	.string "FERNANDA: You look amazing!
"
	.string "That Champion cape really suits you.$"

Route6_UnusedHouse_Text_Sam::
	.string "SAM: Even the ghosts in MASQUERADE
"
	.string "TOWN are singing for you today!$"

Route6_UnusedHouse_Text_Joe::
	.string "JOE: I brought some extra supplies
"
	.string "from the Mart for the party!$"

Route6_UnusedHouse_Text_Zaynab::
	.string "ZAYNAB: I'm so glad FIG is safe.
"
	.string "Now we can finally party!$"

Route6_UnusedHouse_Text_Aliyah::
	.string "ALIYAH: You're the best sister and
"
	.string "the best Champion! Happy Birthday!$"

Route6_UnusedHouse_Text_Aditi::
	.string "ADITI: From DIABLO ISLAND to here,
"
	.string "we wouldn't miss this for anything!$"

Route6_UnusedHouse_Text_ProfTree::
	.string "TREE: Hohoho! A masterpiece of a
"
	.string "day! I've even finished reading\l"
	.string "all my Twilight chapters.\p"
	.string "Happy Birthday, {PLAYER}!$"
