CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
    .string "My husband likes trading POKéMON.\p"
    .string "You're collecting POKéMON for your\n"
    .string "POKéDEX, aren't you?\p"
    .string "Would you please trade with him?$"


CeruleanCity_House3_EventScript_Dontae_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pShe refused to evolve unless I moved to a colder climate. Too much effort!\pWould you like to take this\nAlolan variant?"

CeruleanCity_House3_EventScript_Dontae_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

CeruleanCity_House3_EventScript_Dontae_DeclinedText::
    .string "Oh, okay. Maybe next time!"

CeruleanCity_House3_EventScript_Dontae_NoRoomText::
    .string "You've got no room in your party!"

