PewterCity_House1_Text_Nidoran::
    .string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
    .string "JOHN: CAROLYN and I have been\n"
    .string "living here for a while. It's as\l"
    .string "tough as the city itself!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
    .string "CAROLYN: Mt. Moon is so fascinating!\n"
    .string "I've been researching those fossils\l"
    .string "while JOHN scouts for the GYM.$"

