PewterCity_Gym_Text_BrockIntro::
    .string "You can either walk the plank or\n"
    .string "remove your blouse.{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PewterCity_Gym_Text_BrockDefeat::
    .string "YOU BEAT ME?!\n"
    .string "Take this to remember me by.\p"
    .string "{FONT_NORMAL}{PLAYER} received the BOULDERBADGE\n"
    .string "from FARIS!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}YOU BEAT ME?! Take this to remember\n"
    .string "me by...$"

PewterCity_Gym_Text_TakeThisWithYou::
    .string "Wait!\n"
    .string "Take this to remember me by...$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
    .string "{PLAYER} received a POO BAG\n"
    .string "from FARIS.$"

PewterCity_Gym_Text_ExplainTM39::
    .string "That bag contains some of BOWIE'S\n"
    .string "very special POOP.\p"
    .string "It's so gross that any POKéMON\n"
    .string "exposed to it will lose their\l"
    .string "will to fight and drop a level!\p"
    .string "Use it wisely... or just keep it\n"
    .string "away from me.$"

PewterCity_Gym_Text_BrockPostBattle::
    .string "You have a bright future ahead of\n"
    .string "you as a TRAINER.\p"
    .string "Keep believing in yourself and\n"
    .string "your POKéMON!\p"
    .string "Why don't you head to POOLSIDE CITY\n"
    .string "next? BRYONY will be happy to\l"
    .string "see you!$"

PewterCity_Gym_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"

PewterCity_Gym_Text_LiamIntro::
    .string "Stop right there, kid!\p"
    .string "You're not ready to face FARIS yet!$"

PewterCity_Gym_Text_LiamDefeat::
    .string "Darn!\p"
    .string "Light-years isn't time…\n"
    .string "It measures distance!$"

PewterCity_Gym_Text_LiamPostBattle::
    .string "You're good, but FARIS is on a\n"
    .string "whole other level!$"

PewterCity_Gym_Text_OllieIntro::
    .string "OLLIE: Hey baby! I'm so glad you\n"
    .string "made it here safely.\p"
    .string "I've got a little something for you.\n"
    .string "It reminded me of us.$"

PewterCity_Gym_Text_OllieGiftPewter::
    .string "OLLIE: Here, take this.$"

PewterCity_Gym_Text_OllieAdvice::
    .string "OLLIE: FARIS is a bit... unusual.\n"
    .string "He uses a strange mix of POKéMON.\p"
    .string "Just keep your cool and you'll\n"
    .string "be just fine.\p"
    .string "I'm so proud of you, SHUKTI.\n"
    .string "I know you can make it all the way.$"

PewterCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: Just as I thought!\n"
    .string "You're POKéMON champ material!\p"
    .string "I'm off to handle some business,\n"
    .string "but I'll be keeping an eye on you.$"

PewterCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

PewterCity_Gym_Text_GymStatue::
    .string "PAVEMENT CITY POKéMON GYM\n"
    .string "LEADER: FARIS\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
    .string "PAVEMENT CITY POKéMON GYM\n"
    .string "LEADER: FARIS\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"
