PewterCity_Gym_Text_BrockIntro::
    .string "Hi there! I'm FARIS.\n"
    .string "I'm the LEADER of the PERM-TER CITY GYM.\p"
    .string "I believe in the power of the mind\n"
    .string "and the magic of friendship!\p"
    .string "Are you ready to see what my\n"
    .string "POKéMON can do?\p"
    .string "Let's have a great match!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PewterCity_Gym_Text_BrockDefeat::
    .string "Wow! You're really amazing!\p"
    .string "As proof of your victory, please\n"
    .string "take the BOULDERBADGE.\p"
    .string "{FONT_NORMAL}{PLAYER} received the BOULDERBADGE\n"
    .string "from FARIS!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
    .string "{FONT_MALE}That badge is a symbol of your\n"
    .string "strength and determination.$"

PewterCity_Gym_Text_TakeThisWithYou::
    .string "Wait!\n"
    .string "Take this with you.$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
    .string "{PLAYER} received TM39\n"
    .string "from FARIS.$"

PewterCity_Gym_Text_ExplainTM39::
    .string "A TM, Technical Machine, contains a\n"
    .string "technique for POKéMON.\p"
    .string "Using a TM teaches the move it\n"
    .string "contains to a POKéMON.\p"
    .string "A TM is good for only one use.\p"
    .string "So, when you use one, pick the\n"
    .string "POKéMON carefully.\p"
    .string "Anyways…\n"
    .string "TM39 contains ROCK TOMB.\p"
    .string "It hurls boulders at the foe and\n"
    .string "lowers its SPEED.$"

PewterCity_Gym_Text_BrockPostBattle::
    .string "You have a bright future ahead of\n"
    .string "you as a TRAINER.\p"
    .string "Keep believing in yourself and\n"
    .string "your POKéMON!\p"
    .string "Why don't you head to CURL-ULEAN CITY\n"
    .string "next? BRYONY will be happy to\l"
    .string "see you!$"

PewterCity_Gym_Text_DontHaveRoomForThis::
    .string "You don't have room for this.$"

PewterCity_Gym_Text_LiamIntro::
    .string "Stop right there, kid!\p"
    .string "You're not ready to face FARIS yet!$"

PewterCity_Gym_Text_LiamDefeat::
    .string "Darn!\p"
    .string "Light-years isn't time…\n"
    .string "It measures distance!$"

PewterCity_Gym_Text_LiamPostBattle::
    .string "You're good, but FARIS is on a\n"
    .string "whole other level!$"

PewterCity_Gym_Text_OllieIntro::
    .string "OLLIE: Hey baby! I'm so glad you\n"
    .string "made it here safely.\p"
    .string "I've got a little something for you.\n"
    .string "It reminded me of us.$"

PewterCity_Gym_Text_OllieGiftPewter::
    .string "OLLIE: Here, take this.$"

PewterCity_Gym_Text_OllieAdvice::
    .string "OLLIE: FARIS is into mind games.\n"
    .string "He uses Psychic and Fairy types.\p"
    .string "Just keep your focus and you'll\n"
    .string "blow right through him.\p"
    .string "I'm so proud of you, SHUKTI.\n"
    .string "I know you can make it all the way.$"

PewterCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: Just as I thought!\n"
    .string "You're POKéMON champ material!\p"
    .string "I'm off to handle some business,\n"
    .string "but I'll be keeping an eye on you.$"

PewterCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

PewterCity_Gym_Text_GymStatue::
    .string "PERM-TER CITY POKéMON GYM\n"
    .string "LEADER: FARIS\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
    .string "PERM-TER CITY POKéMON GYM\n"
    .string "LEADER: FARIS\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

