VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
	.string "Hi!\n"
	.string "Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my\n"
	.string "{STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon::
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it\n"
	.string "to me!$"

VermilionCity_House2_Text_ThankYou::
	.string "Thank you!$"

VermilionCity_House2_Text_HowIsMyOldMon::
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"

VermilionCity_House2_EventScript_Elyssa_Intro::
    .string "Aloha! I'm from the ALOLAN TOURISM\nBOARD. We're rehoming some POKéMON.\pHe tried to 'ice' my morning coffee. I prefer it hot!\pWould you like to take this\nAlolan variant?"

VermilionCity_House2_EventScript_Elyssa_Outro::
    .string "Thanks for helping! Hope you visit\nAlola soon!"

VermilionCity_House2_EventScript_Elyssa_DeclinedText::
    .string "Oh, okay. Maybe next time!"

VermilionCity_House2_EventScript_Elyssa_NoRoomText::
    .string "You've got no room in your party!"

