CeladonCity_Text_GotMyKoffingInCinnabar::
    .string "ALISHA: I got my KOFFING in DIABLO\n"
    .string "ISLAND. It's usually nice, but it\l"
    .string "breathes poison when it's angry.\l"
    .string "Kind of like me before coffee!$"

CeladonCity_Text_GymIsGreatFullOfWomen::
    .string "ASHLEY: Heheh! This GYM is great!\n"
    .string "It's full of muscle! DAVID really\l"
    .string "knows how to recruit.$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
    .string "EMPIRE CITY takes pride in its\n"
    .string "efforts to keep the city beautiful.\p"
    .string "That's why the new GAME CORNER is\n"
    .string "so out of fashion!$"

CeladonCity_Text_BlewItAllAtSlots::
    .string "CONNOR: Moan…\n"
    .string "I blew it all at the slots!\p"
    .string "I should have just spent my COINS\n"
    .string "on some new hair color!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
    .string "This is my trusted pal, POLIWRATH.\p"
    .string "It evolved from a POLIWHIRL when\n"
    .string "I used a WATER STONE.$"

CeladonCity_Text_Poliwrath::
    .string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
    .string "What are you staring at?\n"
    .string "Get lost, or I'll show you some\l"
    .string "real EMPIRE power!$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
    .string "Keep out of TEAM ROCKET's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
    .string "TRAINER TIPS\p"
    .string "X ACCURACY boosts focus.\n"
    .string "DIRE HIT jacks up the power.\p"
    .string "Get your supplies at the EMPIRE\n"
    .string "DEPT. STORE!$"

CeladonCity_Text_CitySign::
    .string "EMPIRE CITY\n"
    .string "The City of Rainbow Dreams$"

CeladonCity_Text_GymSign::
    .string "EMPIRE CITY POKéMON GYM\n"
    .string "LEADER: DAVID\l"
    .string "The Bodybuilder Pro!$"

CeladonCity_Text_MansionSign::
    .string "EMPIRE MANSION$"

CeladonCity_Text_DeptStoreSign::
    .string "Find what you need at the\n"
    .string "EMPIRE DEPT. STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
    .string "TRAINER TIPS\p"
    .string "GUARD SPEC. keeps your POKéMON\n"
    .string "fresh and status-free.\p"
    .string "Shop at the EMPIRE DEPT. STORE!$"

CeladonCity_Text_PrizeExchangeSign::
    .string "COINS exchanged for prizes!\n"
    .string "PRIZE EXCHANGE$"

CeladonCity_Text_GameCornerSign::
    .string "ROCKET GAME CORNER\n"
    .string "The playground for grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea::
    .string "Aaaagh, ow…\n"
    .string "I scalded my tongue!\p"
    .string "This nice lady in the MANSION\n"
    .string "gave me some boiling TEA.\p"
    .string "Need some Liquid Death to cool\n"
    .string "down!$"

Text_SoftboiledTeach::
    .string "Hello, there!\p"
    .string "I've seen you about, but I never\n"
    .string "had a chance to chat.\p"
    .string "It must be good luck that brought\n"
    .string "us together finally.\p"
    .string "I'd like to celebrate by teaching\n"
    .string "you the move SOFTBOILED.$"

Text_SoftboiledDeclined::
    .string "I'll always be keeping an eye out\n"
    .string "for you.\p"
    .string "I hope we can chat again.$"

Text_SoftboiledWhichMon::
    .string "So, who's the POKéMON that gets\n"
    .string "the chance to learn SOFTBOILED?$"

Text_SoftboiledTaught::
    .string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
    .string "MATT: Oh, what am I to do…\p"
    .string "Someone stole poor FIG!\p"
    .string "The thief came running this way\n"
    .string "with a tricolour collie, I'm sure\l"
    .string "of it!\p"
    .string "They headed into the GAME CORNER!\n"
    .string "I'm too scared to follow!$"

