ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from MILL TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. TREE, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received TREE'S PARCEL\n"
    .string "from the PokeASDA clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. TREE for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

