ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from CLEAR TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. TREE, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received the TWILIGHT BOX SET\n"
    .string "from the PokeASDA clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. TREE for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"

ViridianCity_Mart_Text_PokeASDA_AuditStart::
    .string "Welcome to PokeASDA!\p"
    .string "We're running a Mystery Shopper\n"
    .string "program to optimize our service.\p"
    .string "If you audit our branches in\n"
    .string "PAVEMENT and POOLSIDE City, you\l"
    .string "might earn a staff discount!\p"
    .string "Please start by checking our\n"
    .string "PAVEMENT CITY branch.$"

