VermilionCity_Gym_Text_LtSurgeIntro::
    .string "Hey, kid! What do you think you're\n"
    .string "doing here?\p"
    .string "You won't live long in combat!\n"
    .string "Not with your puny power!\p"
    .string "I tell you, kid, electric POKéMON\n"
    .string "saved me during the war!\p"
    .string "They zapped my enemies into\n"
    .string "paralysis!\p"
    .string "The same as I'll do to you!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "A little word of advice, kid!\p"
    .string "Electricity is sure powerful!\p"
    .string "But, it's useless against GROUND-\n"
    .string "type POKéMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "The THUNDERBADGE cranks up your\n"
    .string "POKéMON's SPEED!\p"
    .string "It also lets your POKéMON FLY\n"
    .string "lightning-quick anytime, kid!\p"
    .string "You're special, kid!\n"
    .string "Take this!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received TM34\n"
    .string "from LT. SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 contains SHOCK WAVE!\p"
    .string "Teach it to an ELECTRIC POKéMON!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, kid, make room in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Now that's a shocker!\p"
    .string "You're the real deal, kid!\p"
    .string "Fine, then, take the THUNDERBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "When I was in the Army, LT. SURGE\n"
    .string "was my strict CO.\p"
    .string "He was a hard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "It's not easy opening that door.\p"
    .string "LT. SURGE was always famous for\n"
    .string "his cautious nature in the Army.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "LT. SURGE said he hid door\n"
    .string "switches inside something.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "LT. SURGE installed the traps in\n"
    .string "the GYM himself.\p"
    .string "He set up double locks everywhere.\n"
    .string "Let me give you a hint.\p"
    .string "When you open the first lock, the\n"
    .string "second lock is right next to it.$"

VermilionCity_Gym_Text_OllieIntro::
    .string "OLLIE: Missed you! I hope you're\n"
    .string "liking the journey so far.\p"
    .string "I've got a little something for you.\n"
    .string "It's a scale from my heart.$"

VermilionCity_Gym_Text_OllieGiftVermilion::
    .string "OLLIE: Here, take this.$"

VermilionCity_Gym_Text_OllieAdvice::
    .string "OLLIE: LT. SURGE is a war veteran.\n"
    .string "His Electric types are fast!\p"
    .string "But I've seen you battle, SHUKTI.\n"
    .string "You're special. Keep that strength\l"
    .string "up for the big challenges later!$"

VermilionCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: Whew! That match was\n"
    .string "electric!\p"
    .string "You're scaling the heights of the\n"
    .string "POKéMON world. See you soon!$"

VermilionCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

VermilionCity_Gym_Text_GymStatue::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "VERMILION POKéMON GYM\n"
    .string "LEADER: LT. SURGE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nope!\n"
    .string "There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

