VermilionCity_Gym_Text_LtSurgeIntro::
    .string "HRISHI: Stop right there!\n"
    .string "You think you can just walk in here\l"
    .string "without a solid strategy?\p"
    .string "I've optimized this gym for maximum\n"
    .string "efficiency and voltage!\p"
    .string "My electric POKéMON will short-\n"
    .string "circuit your entire team!\p"
    .string "Prepare for a total system reboot!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
    .string "System error... I didn't account\n"
    .string "for your performance metrics.\p"
    .string "But remember: even the best\n"
    .string "circuits need grounding. Watch\l"
    .string "out for GROUND-types!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
    .string "The BURNOUTBADGE overclock's your\n"
    .string "POKéMON's SPEED!\p"
    .string "It also lets your POKéMON FLY\n"
    .string "anywhere in the blink of an eye!\p"
    .string "You've got potential. Take this\n"
    .string "utility script, too!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
    .string "{PLAYER} received TM34\n"
    .string "from HRISHI.$"

VermilionCity_Gym_Text_ExplainTM34::
    .string "TM34 contains SHOCK WAVE!\p"
    .string "It's an unavoidable attack.\n"
    .string "Direct and efficient!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
    .string "Yo, clear some cache in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
    .string "Critical failure!\p"
    .string "You've bypassed all my security!\p"
    .string "Fine, then, take the BURNOUTBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
    .string "HRISHI is a hard taskmaster.\n"
    .string "Everything has to be perfect.$"

VermilionCity_Gym_Text_TuckerDefeat::
    .string "Stop!\n"
    .string "Your logic is sound!$"

VermilionCity_Gym_Text_TuckerPostBattle::
    .string "It's not easy opening that door.\p"
    .string "HRISHI installed the security\n"
    .string "protocols himself.$"

VermilionCity_Gym_Text_BailyIntro::
    .string "I'm a lightweight, but I'm good\n"
    .string "with electricity!\p"
    .string "That's why I joined this GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
    .string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
    .string "Okay, I'll talk!\p"
    .string "HRISHI said he hid door\n"
    .string "switches inside something.$"

VermilionCity_Gym_Text_DwayneIntro::
    .string "This is no place for kids!\n"
    .string "Not even if you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
    .string "Wow!\n"
    .string "Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
    .string "HRISHI installed the traps in\n"
    .string "the GYM himself.\p"
    .string "He set up double locks everywhere.\n"
    .string "Let me give you a hint.\p"
    .string "When you open the first lock, the\n"
    .string "second lock is right next to it.$"

VermilionCity_Gym_Text_OllieIntro::
    .string "OLLIE: Missed you! I hope you're\n"
    .string "liking the journey so far.\p"
    .string "I've got a little something for you.\n"
    .string "It's a scale from my heart.$"

VermilionCity_Gym_Text_OllieGiftVermilion::
    .string "OLLIE: Here, take this.$"

VermilionCity_Gym_Text_OllieAdvice::
    .string "OLLIE: HRISHI is a real pro.\n"
    .string "His Electric types are fast!\p"
    .string "But I've seen you battle, SHUKTI.\n"
    .string "You're special. Keep that strength\l"
    .string "up for the big challenges later!$"

VermilionCity_Gym_Text_OlliePostVictory::
    .string "OLLIE: Whew! That match was\n"
    .string "electric!\p"
    .string "You're scaling the heights of the\n"
    .string "POKéMON world. See you soon!$"

VermilionCity_Gym_Text_NoRoomForGift::
    .string "OLLIE: Oh, your BAG is full!\n"
    .string "I'll hold onto this for you.$"

VermilionCity_Gym_Text_GymStatue::
    .string "BURNOUT CITY POKéMON GYM\n"
    .string "LEADER: HRISHI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
    .string "BURNOUT CITY POKéMON GYM\n"
    .string "LEADER: HRISHI\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
    .string "Nope!\n"
    .string "There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
    .string "Hey! There's a switch under the\n"
    .string "trash! Turn it on!\p"
    .string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
    .string "ガサゴソ‥！\n"
    .string "おっと！　ゴミばこの　そこに\l"
    .string "また　スイッチが　あった！\l"
    .string "おして　みよう！　‥　ポチッとな$"

VermilionCity_Gym_Text_SecondLockOpened::
    .string "The second electric lock opened!\n"
    .string "The motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
    .string "Nope!\n"
    .string "There's only trash here.\p"
    .string "Hey!\n"
    .string "The electric locks were reset!$"

