SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
    .string "Huh?\n"
    .string "A new member?$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
    .string "Welcome to the official\n"
    .string "TWILIGHT FAN CLUB!\p"
    .string "I'm the President. We spend all day\n"
    .string "debating the deep philosophical\l"
    .string "themes of the series.\p"
    .string "Like... which boy is hotter.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
    .string "TEAM JACOB for life!\p"
    .string "Have you seen his abs? They're like\n"
    .string "Geodudes!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
    .string "EDWARD is the only choice.\n"
    .string "He sparkles! My POKéMON should\l"
    .string "sparkle too.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
    .string "I thought this was a FIGHTING\n"
    .string "DOJO fan club. I'm so confused.\p"
    .string "Who is this Edward guy? Does he\n"
    .string "know Karate?$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
    .string "BELLA is so relatable.\n"
    .string "I also can't decide between two\l"
    .string "very dangerous options.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
    .string "Do you think Vampires use\n"
    .string "GHOST POKéMON or DARK POKéMON?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
    .string "Can you autograph my copy of\n"
    .string "New Moon?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
    .string "I'm writing a fanfic where RED is\n"
    .string "actually a vampire.$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
    .string "Team Jacob!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
    .string "Team Edward!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
    .string "Team Bella!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
    .string "Twilight is the greatest story\n"
    .string "ever told.$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
    .string "Have you been to Forks?$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
    .string "Are you Team Edward or\n"
    .string "Team Jacob?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
    .string "You haven't even read the books?$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
    .string "We're the biggest fan club in\n"
    .string "SAFFRON-SWAN CITY!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
    .string "I want to be a vampire!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
    .string "I'm still a fan!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
    .string "Bella is my hero.$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
    .string "I love Twilight!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
    .string "Sparkle!$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
    .string "Cool!$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
    .string "Twilight forever!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
    .string "Edward!$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
    .string "Jacob!$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
    .string "Bella!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
    .string "President!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
    .string "Fire!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
    .string "Talk!$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
    .string "Amazing!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
    .string "Only fan!$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
    .string "Dignity!$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
    .string "Heart!$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
    .string "Education!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
    .string "Fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
    .string "Respect!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
    .string "Never!$"
