ViridianCity_House_Text_NicknamingIsFun::
    .string "CHRIS: This place is perfect for us.\n"
    .string "There's plenty of room for all our\l"
    .string "outdoor gear, and ELLIE loves the\l"
    .string "view of the city!$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
    .string "ELLIE: Shhh! I'm busy yearning at\n"
    .string "the TV. I just love hockey so much!$"

ViridianCity_House_Text_Speary::
    .string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
    .string "SPEAROW\n"
    .string "Name: SPEARY$"

ViridianCity_House_Text_HockeyTV::
    .string "It's a hockey game!\p"
    .string "The commentary is so loud you can\n"
    .string "barely hear yourself think.$"
